import { formatTime } from "./i18n";
import { errorKey } from "./api";
import { DebugAttempts } from "./playground";
import { tr, trError, jobLabel } from "./i18n";
import { useState } from "react";
import { ArrowClockwiseIcon, CheckIcon, ClockIcon, ListChecksIcon, PauseIcon, SpinnerGapIcon, StopIcon, XIcon } from "@phosphor-icons/react";
import { useI18n } from "./i18n";
import { api, useResource, relative, number, errorText, submit } from "./api";
import { Badge, Button, Confirm, Empty, Header, IconButton, Modal, Panel } from "./components";
import type { PublicJob } from "../shared/types";
const statuses:Record<string,string>={get queued() { return tr("state.queued"); },get running() { return tr("state.processing"); },get waiting() { return tr("state.retrying"); },get completed() { return tr("common.done"); },get failed() { return tr("state.failed"); },get cancelled() { return tr("state.cancelled"); },get uncertain() { return tr("state.review"); }};
const phases:Record<string,string>={get queued() { return tr("state.queued"); },get starting() { return tr("job.phase.start"); },get discover() { return tr("job.phase.discover"); },get verify() { return tr("job.phase.verify"); },get index() { return tr("job.phase.index"); },get search() { return tr("common.search"); },get connect() { return tr("common.connect"); },get catalog() { return tr("job.phase.catalog"); },get request() { return tr("traffic.request.title"); },get stream() { return tr("job.phase.receive"); },get retry() { return tr("state.retrying"); },get execute() { return tr("common.execute"); },get completed() { return tr("common.done"); },get stopped() { return tr("state.stopped"); },get recovery() { return tr("common.restore"); }};
export function JobIndicator({open}:{open:()=>void}){const jobs=useResource<PublicJob[]>("/jobs",1500);const active=jobs.data?.filter(j=>["queued","running","waiting"].includes(j.status))||[];return <button className={`job-indicator ${active.length?"active":""}`} onClick={open} aria-label={tr("page.jobs.title")}><ListChecksIcon size={16}/>{active.length>0&&<span>{active.length}</span>}</button>;}
export function JobsPage(){
  const { t } = useI18n();const jobs=useResource<PublicJob[]>("/jobs",1500);const [selected,setSelected]=useState<string>();return <><div className="page-heading"><div><div className="eyebrow">{t("page.jobs.eyebrow")}</div><h1>{t("page.jobs.title")}</h1></div><IconButton label={tr("job.action.refresh")} onClick={jobs.refresh}><ArrowClockwiseIcon size={18}/></IconButton></div><Panel><Header title={tr("nav.jobs")} count={jobs.data?.length}/>{jobs.data?.length?<div className="job-list">{jobs.data.map(job=><button key={job.id} className="job-row" onClick={()=>setSelected(job.id)}><span className={`job-symbol ${job.status}`} >{job.status==="running"?<SpinnerGapIcon size={20} className="spin"/>:job.status==="completed"?<CheckIcon size={20}/>:<ClockIcon size={20}/>}</span><div className="job-row-content"><strong>{jobLabel(job)}</strong><span>{phases[job.phase]||job.phase}{job.currentItem?` · ${job.currentItem}`:""}</span>{job.total!==null&&job.total>0&&["running","waiting"].includes(job.status)&&<progress max={job.total} value={job.processed}/>}</div><span className="mono muted">{job.total===null?number(job.processed):`${number(job.processed)} / ${number(job.total)}`}</span><Badge tone={job.status==="completed"?"green":"muted"}>{statuses[job.status]}</Badge><time className="mono muted">{relative(job.updatedAt)}</time></button>)}</div>:<Empty icon={<ListChecksIcon size={28}/>} title={tr("job.empty")}/>}</Panel>{selected&&<JobDetail id={selected} close={()=>setSelected(undefined)} changed={jobs.refresh}/>}</>;}
function JobDetail({id,close,changed}:{id:string;close:()=>void;changed:()=>void}){const job=useResource<PublicJob&{result:unknown}>(`/jobs/${id}`,1000);const [error,setError]=useState("");const value=job.data;return <Modal title={value?jobLabel(value):tr("nav.jobs")} open wide onOpenChange={close}>{value&&<><div className="session-detail-tools"><Badge>{statuses[value.status]}</Badge><span className="mono muted">{value.kind}</span></div><dl className="detail-list"><div><dt>{tr("job.field.phase")}</dt><dd>{phases[value.phase]||value.phase}</dd></div><div><dt>{tr("job.field.processed")}</dt><dd className="mono">{number(value.processed)}{value.total!==null?` / ${number(value.total)}`:""}</dd></div><div><dt>{tr("traffic.attempts.title")}</dt><dd className="mono">{value.attempts}</dd></div>{value.currentItem&&<div><dt>{tr("job.field.current")}</dt><dd>{value.currentItem}</dd></div>}{value.status==="waiting"&&<div><dt>{tr("job.field.nextRetry")}</dt><dd>{formatTime(value.nextRunAt)}</dd></div>}</dl>{value.error&&<div className="form-warning">{value.error}</div>}{value.kind==="model.debug"&&<DebugAttempts jobId={id}/>}
{value.result!==null&&<pre className="run-output job-result">{JSON.stringify(value.result,null,2)}</pre>}{error&&<div className="form-error">{trError(error)}</div>}<div className="form-actions">{["running","queued","waiting"].includes(value.status)?<Button icon={<StopIcon size={15}/>} onClick={async()=>{try{await api(`/jobs/${id}/cancel`,{method:"POST"});changed();job.refresh();}catch(e){setError(errorKey(e));}}}>{tr("common.cancel")}</Button>:<Confirm title={tr("job.confirm.repeat")} onConfirm={async()=>{await submit(`/jobs/${id}/retry`,{confirmed:true});changed();close();}}><button className="button"><ArrowClockwiseIcon size={15}/>{tr("job.action.repeat")}</button></Confirm>}</div></>}</Modal>;}
