import { tr, trError } from "./i18n";
import { useState } from "react";
import { CheckIcon, ClockIcon, PlugsConnectedIcon, ShieldCheckIcon, StopIcon } from "@phosphor-icons/react";
import { api, useResource, errorKey, errorText, relative } from "./api";
import { Badge, Button, Confirm, Empty, Modal, Panel } from "./components";
import type { PublicMcpCall } from "../shared/types";

const statuses: Record<string, string> = { get pending() { return tr("state.approval"); }, get approved() { return tr("state.approved"); }, get running() { return tr("state.executing"); }, get completed() { return tr("common.done"); }, get rejected() { return tr("state.rejected"); }, get cancelled() { return tr("state.cancelled"); }, get failed() { return tr("state.failed"); }, get uncertain() { return tr("state.uncertain"); } };
export function McpCalls({ inbox = false }: { inbox?: boolean }) {
  const calls = useResource<PublicMcpCall[]>(`/mcp-calls${inbox ? "?status=pending" : ""}`, 2000);
  const [selected, setSelected] = useState<string>();
  if (inbox && !calls.data?.length && !selected) return null;
  return <>{inbox ? <div className="mcp-approval-list">{calls.data?.map(call => <Panel key={call.id} className="approval-card"><div className="approval-title"><PlugsConnectedIcon size={18}/><strong>{call.connectionName} / {call.name}</strong><time className="mono">{relative(call.createdAt)}</time></div><div className="approval-origin"><Badge>{call.clientName}</Badge><span className="mono">{call.project?.split("/").at(-1) || tr("scope.global")}</span></div><div className="approval-actions"><Button onClick={() => setSelected(call.id)}>{tr("approval.action.review")}</Button></div></Panel>)}</div> : <div className="mcp-call-list">{calls.data?.map(call => <button key={call.id} className="mcp-call-row" onClick={() => setSelected(call.id)}><span className="request-symbol"><PlugsConnectedIcon size={16}/></span><div><strong>{call.name}</strong><span>{call.connectionName} · {call.clientName}</span></div><Badge tone={call.status === "completed" ? "green" : "muted"}>{statuses[call.status]}</Badge><time className="mono">{relative(call.createdAt)}</time></button>)}{!calls.data?.length && <Empty icon={<PlugsConnectedIcon size={27} weight="light"/>} title={tr("mcp.calls.empty")}/>}</div>}{selected && <McpCallDetail id={selected} close={() => setSelected(undefined)} changed={calls.refresh}/>}</>;
}
function McpCallDetail({ id, close, changed }: { id: string; close: () => void; changed: () => void }) {
  const request = useResource<PublicMcpCall & { arguments: unknown; result: unknown }>(`/mcp-calls/${id}`, 2000);
  const [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function decide(accept: boolean) { setBusy(true); try { await api(`/mcp-calls/${id}/decide`, { method: "POST", body: JSON.stringify({ accept }) }); request.refresh(); changed(); } catch (error) { setError(errorKey(error)); } finally { setBusy(false); } }
  const call = request.data;
  return <Modal title={call ? `${call.connectionName} / ${call.name}` : tr("mcp.calls.title")} wide open onOpenChange={close}>{call && <><div className="session-detail-tools"><Badge tone={call.status === "completed" ? "green" : "muted"}>{statuses[call.status]}</Badge><Badge>{call.kind}</Badge><span className="mono muted">{call.clientName}</span></div>{call.project && <div className="mcp-detail-project mono">{call.project}</div>}<div className="mcp-payload-label mono">ARGUMENTS</div><pre className="run-output">{JSON.stringify(call.arguments, null, 2)}</pre>{call.error && <div className="form-warning">{call.error}</div>}{call.result !== null && <><div className="mcp-payload-label mono">RESULT</div><pre className="run-output">{JSON.stringify(call.result, null, 2)}</pre></>}{error && <div className="form-error" role="alert">{trError(error)}</div>}{call.status === "pending" && <div className="form-actions"><span className="approval-expiry"><ClockIcon size={13}/>{Math.max(0, Math.ceil((call.expiresAt - Date.now()) / 1000))}s</span><Button busy={busy} onClick={() => void decide(false)}>{tr("common.reject")}</Button><Button className="primary" icon={<ShieldCheckIcon size={15}/>} busy={busy} onClick={() => void decide(true)}>{tr("approval.action.once")}</Button></div>}{["running", "approved"].includes(call.status) && <div className="form-actions"><Confirm title={tr("mcp.confirm.cancel")} onConfirm={async () => { await api(`/mcp-calls/${id}/cancel`, { method: "POST" }); request.refresh(); changed(); }}><button className="button danger"><StopIcon size={15}/>{tr("common.cancel")}</button></Confirm></div>}</>}</Modal>;
}
