import { formatTime } from "./i18n";
import { tr, trError } from "./i18n";
import { useState } from "react";
import { ArrowRightIcon, CheckIcon, ClockIcon, FingerprintIcon, PauseIcon, PlayIcon, PlusIcon, ShieldCheckIcon, StopIcon, TerminalWindowIcon, WarningCircleIcon, XIcon, PaperPlaneTiltIcon, TargetIcon } from "@phosphor-icons/react";
import { McpCalls } from "./mcp-calls";
import { McpGrantEditor } from "./mcp-access";
import { useI18n } from "./i18n";
import { api, useResource, errorKey, errorText, relative, money, number } from "./api";
import { Badge, Button, Confirm, Dropdown, Empty, Field, Header, IconButton, Modal, Panel } from "./components";
import type { Run, RunApproval, RunEvent, BudgetSummary, ModelRoute, RunStatus } from "../shared/types";

const labels: Record<RunStatus, string> = { get queued() { return tr("state.waiting"); }, get starting() { return tr("state.starting"); }, get running() { return tr("state.running"); }, get evaluating() { return tr("state.evaluating"); }, get waiting_for_input() { return tr("state.candidate"); }, get waiting_for_approval() { return tr("state.approval"); }, get paused() { return tr("state.paused"); }, get blocked() { return tr("state.blocked"); }, get budget_exhausted() { return tr("state.exhausted"); }, get completed() { return tr("common.done"); }, get failed() { return tr("state.failed"); }, get cancelled() { return tr("state.stopped"); } };
const reasons: Record<string, string> = { get user_paused() { return tr("run.reason.paused"); }, get user_cancelled() { return tr("run.reason.stopped"); }, get time_limit() { return tr("run.reason.time"); }, get turn_limit() { return tr("run.reason.turns"); }, get cost_limit() { return tr("run.reason.cost"); }, get token_limit() { return tr("field.tokenLimit"); }, get no_observed_progress() { return tr("run.reason.noProgress"); }, get completion_confirmation_required() { return tr("run.reason.confirmation"); }, get approval_denied() { return tr("run.reason.denied"); }, get gateway_restarted() { return tr("run.reason.restarted"); }, get gateway_shutdown() { return tr("run.reason.shutdown"); }, get native_permission_required() { return tr("run.reason.nativePermission"); }, get criteria_satisfied() { return tr("run.reason.criteria"); }, get turn_completed() { return tr("run.reason.turnComplete"); }, get user_confirmed() { return tr("run.reason.confirmed"); }, get budget_exhausted() { return tr("error.budget"); }, get price_required() { return tr("run.reason.unpriced"); } };
const activeStatuses = ["queued", "starting", "running", "evaluating", "waiting_for_approval"];
const resumableStatuses = ["paused", "blocked", "budget_exhausted", "failed", "waiting_for_input"];
const events: Record<string, string> = { get "run.started"() { return tr("job.phase.start"); }, get "turn.started"() { return tr("run.event.turnStart"); }, get "turn.completed"() { return tr("run.event.turnEnd"); }, get "goal.evaluated"() { return tr("run.event.evaluate"); }, get "approval.requested"() { return tr("run.event.approvalRequested"); }, get "approval.decided"() { return tr("run.event.approvalDecided"); }, get "steer.authorized"() { return tr("run.event.steered"); }, get "resume.authorized"() { return tr("common.restore"); }, get "pause.requested"() { return tr("run.event.pauseRequested"); }, get "stop.requested"() { return tr("run.event.stopRequested"); }, get "goal.confirmed"() { return tr("run.event.confirmed"); }, get "native.turn"() { return tr("run.event.nativeTurn"); } };
function Status({ value }: { value: RunStatus }) { return <span className={`status status-${value}`}><i/>{labels[value]}</span>; }
export function RunsPage() {
  const { t } = useI18n();
  const runs = useResource<Run[]>("/runs", 2000), approvals = useResource<RunApproval[]>("/approvals", 2000);
  const [creating, setCreating] = useState(false), [selected, setSelected] = useState<string>();
  const [error, setError] = useState("");
  const active = runs.data?.filter(r => activeStatuses.includes(r.status)).length || 0;
  const refresh = () => { runs.refresh(); approvals.refresh(); };
  const act = async (id: string, action: string) => { try { await api(`/runs/${id}/${action}`, { method: "POST" }); refresh(); } catch (error) { setError(errorKey(error)); } };
  return <><div className="page-heading"><div><div className="eyebrow">{t("page.runs.eyebrow")}</div><h1>{t("page.runs.title")}</h1></div><Button className="primary" icon={<PlusIcon size={16}/>} onClick={() => setCreating(true)}>{tr("common.run")}</Button></div>
    {(error || runs.error) && <div role="alert" className="error-banner"><span>{error || errorText(new Error(runs.error))}</span><button className="text-button" onClick={() => { setError(""); refresh(); }}>{tr("common.retry")}</button></div>}
    <div className="runtime-strip"><div><span className="live-dot"/><strong>{active}</strong><span>{tr("common.run")}</span></div><div><ShieldCheckIcon size={15}/><strong>{approvals.data?.length || 0}</strong><span>{tr("status.pending")}</span></div><div><CheckIcon size={15}/><strong>{runs.data?.filter(r => r.status === "completed").length || 0}</strong><span>{tr("common.done")}</span></div></div>
    <McpCalls inbox/>
    {!!approvals.data?.length && <div className="approval-inbox">{approvals.data.map(approval => <ApprovalCard key={approval.id} item={approval} refresh={refresh}/>)}</div>}
    <Panel><Header title={tr("nav.jobs")} count={runs.data?.length}/>{runs.data?.length ? <div className="runs-list">{runs.data.map(run => <div className="run-row" key={run.id}><button className="run-main" onClick={() => setSelected(run.id)}><span className={`run-icon ${run.status === "running" ? "running" : ""}`}>{run.controls.mode === "goal" ? <TargetIcon size={20} weight="light"/> : <PlayIcon size={19} weight="light"/>}</span><div><strong>{run.goal}</strong><span><Badge>{run.agent}</Badge><span className="mono muted">{run.workspace.split("/").at(-1)}</span><span className="mono muted">{run.turnCount}/{run.controls.maxTurns}</span></span></div></button><Status value={run.status}/><div className="run-row-controls">{activeStatuses.includes(run.status) ? <><IconButton label={tr("run.action.pause")} onClick={() => void act(run.id, "pause")}><PauseIcon size={17}/></IconButton><Confirm title={tr("run.confirm.stop")} onConfirm={() => act(run.id, "stop")}><button className="icon-button danger-icon" aria-label={tr("run.action.stop")}><StopIcon size={17}/></button></Confirm></> : resumableStatuses.includes(run.status) ? <IconButton label={tr("run.action.resume")} onClick={() => setSelected(run.id)}><PlayIcon size={17}/></IconButton> : <span className="mono muted">{relative(run.updatedAt)}</span>}</div></div>)}</div> : <Empty icon={<PlayIcon size={28} weight="thin"/>} title={tr("job.empty")} action={<Button onClick={() => setCreating(true)} icon={<PlusIcon size={15}/>}>{tr("run.action.create")}</Button>}/>}</Panel>
    {creating && <RunForm close={() => setCreating(false)} saved={id => { setCreating(false); setSelected(id); refresh(); }}/>} {selected && <RunDetails id={selected} close={() => setSelected(undefined)} changed={refresh}/>}
  </>;
}
function RunForm({ close, saved }: { close: () => void; saved: (id: string) => void }) {
  const [mcpGrants, setMcpGrants] = useState<import("../shared/types").McpGrant[]>([]), [memoryAccess, setMemoryAccess] = useState(false);
  const routes = useResource<ModelRoute[]>("/routes");
  const [agent, setAgent] = useState("codex"), [mode, setMode] = useState("goal"), [goal, setGoal] = useState(""), [workspace, setWorkspace] = useState(""), [routeId, setRouteId] = useState("");
  const [permission, setPermission] = useState("read-only"), [minutes, setMinutes] = useState("30"), [turns, setTurns] = useState("20"), [budget, setBudget] = useState(""), [tokens, setTokens] = useState("");
  const [criteria, setCriteria] = useState<{ path: string; contains: string }[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const available = routes.data?.filter(r => r.enabled && (agent === "pi" ? r.protocol !== "gemini" : r.protocol === (agent === "codex" ? "responses" : "messages"))) || [];
  return <Modal title={tr("run.create.title")} open onOpenChange={close}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); try {
    const run = await api<Run>("/runs", { method: "POST", body: JSON.stringify({ agent, goal, workspace, routeId: routeId || available[0]?.id, timeoutSeconds: Number(minutes) * 60,
      controls: { mcpGrants: agent === "pi" ? [] : mcpGrants, memoryAccess: agent === "pi" ? false : memoryAccess, mode, maxTurns: mode === "turn" ? 1 : Number(turns), maxNoProgress: 3, budgetMicros: budget ? Math.round(Number(budget) * 1000000) : null, tokenLimit: tokens ? Number(tokens) : null, permission, completionFiles: criteria.map(c => ({ path: c.path, ...(c.contains ? { contains: c.contains } : {}) })) } }) }); saved(run.id);
  } catch (error) { setError(errorKey(error)); } finally { setBusy(false); } }}>
    <div className="form-grid"><Field label="Agent"><Dropdown value={agent} onChange={v => { setAgent(v); setRouteId(""); if (v === "pi") setPermission("read-only"); }} items={[{ value: "codex", label: "Codex" }, { value: "claude", label: "Claude Code" }, { value: "pi", label: "Pi" }]}/></Field><Field label={tr("nav.models")}><Dropdown value={routeId || available[0]?.id || ""} onChange={setRouteId} items={available.map(r => ({ value: r.id, label: r.alias }))}/></Field></div>
    <Field label={tr("route.field.target")}><textarea rows={3} autoFocus required value={goal} onChange={e => setGoal(e.target.value)}/></Field><Field label={tr("run.field.workspace")}><input className="mono" required value={workspace} onChange={e => setWorkspace(e.target.value)} placeholder="/path/to/project"/></Field>
    <div className="form-grid"><Field label={tr("run.field.mode")}><Dropdown value={mode} onChange={setMode} items={[{ value: "goal", label: tr("run.mode.goal") }, { value: "turn", label: tr("run.mode.turn") }]}/></Field><Field label={tr("run.field.permission")}><Dropdown value={permission} onChange={setPermission} items={agent === "pi" ? [{ value: "read-only", label: tr("run.permission.toolsReadOnly") }] : [{ value: "read-only", label: tr("run.permission.readOnly") }, { value: "workspace-write", label: tr("run.permission.workspaceWrite") }]}/></Field><Field label={tr("run.field.timeLimit")}><input type="number" min="1" max="1440" required value={minutes} onChange={e => setMinutes(e.target.value)}/></Field><Field label={tr("run.field.turnLimit")}><input type="number" min="1" max="1000" disabled={mode === "turn"} value={mode === "turn" ? "1" : turns} onChange={e => setTurns(e.target.value)}/></Field><Field label={tr("field.budgetUsd")}><input type="number" min="0" step=".01" value={budget} onChange={e => setBudget(e.target.value)} placeholder={tr("common.unlimited")}/></Field><Field label={tr("field.tokenLimit")}><input type="number" min="1" value={tokens} onChange={e => setTokens(e.target.value)} placeholder={tr("common.unlimited")}/></Field></div>
    {mode === "goal" && <div className="completion-editor"><div className="completion-heading"><span>{tr("run.criteria.title")}</span><button type="button" className="text-button" onClick={() => setCriteria([...criteria, { path: "", contains: "" }])}><PlusIcon size={14}/>{tr("run.criteria.file")}</button></div>{criteria.map((criterion, i) => <div className="criterion-row" key={i}><input aria-label={tr("run.criteria.pathLabel", { number: i + 1 })} className="mono" placeholder={tr("run.criteria.relativePath")} required value={criterion.path} onChange={e => setCriteria(criteria.map((c, n) => n === i ? { ...c, path: e.target.value } : c))}/><input aria-label={tr("run.criteria.containsLabel", { number: i + 1 })} placeholder={tr("run.criteria.contains")} value={criterion.contains} onChange={e => setCriteria(criteria.map((c, n) => n === i ? { ...c, contains: e.target.value } : c))}/><IconButton type="button" label={tr("run.criteria.remove")} onClick={() => setCriteria(criteria.filter((_, n) => n !== i))}><XIcon size={15}/></IconButton></div>)}{!criteria.length && <Badge>{tr("run.criteria.userConfirmation")}</Badge>}</div>}
    {agent !== "pi" && <details className="client-mcp-details"><summary>{tr("mcp.access.title")}</summary><McpGrantEditor grants={mcpGrants} onChange={setMcpGrants} memory={memoryAccess} onMemory={setMemoryAccess}/></details>}
    {error && <div role="alert" className="form-error">{trError(error)}</div>}<div className="form-actions"><Button type="button" onClick={close}>{tr("common.cancel")}</Button><Button type="submit" className="primary" busy={busy} disabled={!available.length}><PlayIcon size={14}/>{tr("common.run")}</Button></div>
  </form></Modal>;
}
export function RunDetails({ id, close, changed }: { id: string; close: () => void; changed: () => void }) {
  const resource = useResource<Run>(`/runs/${id}`, 1500), history = useResource<RunEvent[]>(`/runs/${id}/events`, 2500), funds = useResource<BudgetSummary>(`/runs/${id}/budget`, 2500);
  const [message, setMessage] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false), [extra, setExtra] = useState("5"), [minutes, setMinutes] = useState("10"), [budget, setBudget] = useState("");
  const run = resource.data;
  async function act(action: string, data?: object) {
    setBusy(true); setError("");
    try { await api(`/runs/${id}/${action}`, { method: "POST", ...(data ? { body: JSON.stringify(data) } : {}) }); resource.refresh(); history.refresh(); changed(); setMessage(""); }
    catch (error) { setError(errorKey(error)); } finally { setBusy(false); }
  }
  return <Modal title={run?.agent || tr("common.run")} wide open onOpenChange={close}>{run && <><div className="run-detail-heading"><Status value={run.status}/><span className="mono muted">{run.turnCount} / {run.controls.maxTurns} TURNS</span></div><h3 className="run-goal">{run.goal}</h3><div className="run-meters"><div><span>{tr("field.cost")}</span><strong className="mono">{money(funds.data?.costMicros || 0)}{run.controls.budgetMicros !== null ? ` / ${money(run.controls.budgetMicros)}` : ""}</strong></div><div><span>Token</span><strong className="mono">{number(funds.data?.tokens || 0)}</strong></div><div><span>{tr("budget.reserved")}</span><strong className="mono">{money(funds.data?.heldMicros || 0)}</strong></div></div>{run.stopReason && <div className="stop-reason"><ClockIcon size={14}/>{reasons[run.stopReason] || run.stopReason}</div>}{error && <div className="form-error" role="alert">{trError(error)}</div>}
    <div className="run-controls">{activeStatuses.includes(run.status) ? <><Button busy={busy} onClick={() => void act("pause")} icon={<PauseIcon size={15}/>}>{tr("common.pause")}</Button><Confirm title={tr("run.confirm.stop")} onConfirm={() => act("stop")}><button className="button danger"><StopIcon size={15}/>{tr("common.stop")}</button></Confirm></> : resumableStatuses.includes(run.status) ? <><Field label={tr("run.resume.extraTurns")}><input type="number" min="1" max="1000" value={extra} onChange={e => setExtra(e.target.value)}/></Field><Field label={tr("run.resume.extraTime")}><input type="number" min="1" max="1440" value={minutes} onChange={e => setMinutes(e.target.value)}/></Field><Field label={tr("run.resume.totalBudget")}><input type="number" min="0" step=".01" placeholder={run.controls.budgetMicros !== null ? String(run.controls.budgetMicros / 1000000) : tr("common.unlimited")} value={budget} onChange={e => setBudget(e.target.value)}/></Field><Button className="primary" busy={busy} onClick={() => void act("resume", { message: message || undefined, extraTurns: Number(extra), extraSeconds: Number(minutes) * 60, ...(budget ? { budgetMicros: Math.round(Number(budget) * 1000000) } : {}) })} icon={<PlayIcon size={14}/>}>{tr("common.resume")}</Button>{["waiting_for_input", "paused", "blocked"].includes(run.status) && <Confirm title={tr("run.confirm.complete")} onConfirm={() => act("complete")}><button className="button"><CheckIcon size={15}/>{tr("common.done")}</button></Confirm>}</> : null}</div>
    {(run.status === "running" && run.agent !== "claude" || resumableStatuses.includes(run.status)) && <form className="steering-input" onSubmit={e => { e.preventDefault(); if (run.status === "running") void act("steer", { message }); }}><input aria-label={tr("run.steer.label")} placeholder={run.status === "running" ? tr("run.steer.placeholder") : tr("run.resume.placeholder")} value={message} onChange={e => setMessage(e.target.value)}/>{run.status === "running" && <IconButton label={tr("run.steer.send")} type="submit" disabled={!message.trim() || busy}><PaperPlaneTiltIcon size={18}/></IconButton>}</form>}
    <details className="run-events"><summary>{tr("run.events.title")} <span className="mono">{history.data?.length || 0}</span></summary><div>{history.data?.filter(e => e.kind !== "native.item").map(e => <div className="run-event" key={e.id}><span className="mono">{e.turn.toString().padStart(2, "0")}</span><strong>{events[e.kind] || (e.kind.startsWith("run.") ? labels[e.kind.slice(4) as RunStatus] : e.kind)}</strong><time className="mono">{formatTime(e.createdAt)}</time></div>)}</div></details>
    <pre className="run-output">{run.output || "…"}</pre></>}</Modal>;
}
function ApprovalCard({ item, refresh }: { item: RunApproval; refresh: () => void }) {
  const [expanded, setExpanded] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(""), [answers, setAnswers] = useState<Record<string, string>>({});
  const questions = Array.isArray(item.payload.questions) ? item.payload.questions as { id: string; question: string; options?: { label: string; description?: string }[] }[] : [];
  async function answer(accept: boolean) {
    setBusy(true); setError("");
    try { await api(`/approvals/${item.id}`, { method: "POST", body: JSON.stringify({ accept, ...(item.kind === "input" ? { answers: Object.fromEntries(Object.entries(answers).map(([key, value]) => [key, [value]])), ...(item.method === "pi/input" ? { value: answers.value } : {}) } : {}) }) }); refresh(); }
    catch (error) { setError(errorKey(error)); } finally { setBusy(false); }
  }
  return <Panel className="approval-card"><div className="approval-title"><ShieldCheckIcon size={19}/><strong>{item.kind === "input" ? tr("approval.input.title") : item.kind === "file" ? tr("approval.file.title") : tr("approval.command.title")}</strong><span className="mono">{relative(item.createdAt)}</span></div><pre className="approval-command">{typeof item.payload.command === "string" ? item.payload.command : typeof item.payload.reason === "string" ? item.payload.reason : item.method}</pre><button className="text-button" onClick={() => setExpanded(!expanded)}>{expanded ? tr("common.collapse") : tr("approval.action.inspect")}</button>{expanded && <pre className="approval-payload">{JSON.stringify(item.payload, null, 2)}</pre>}{questions.map(q => <Field label={q.question} key={q.id}>{q.options && <div className="answer-options">{q.options.map(o => <button key={o.label} type="button" className={`button ${answers[q.id] === o.label ? "primary" : ""}`} onClick={() => setAnswers({ ...answers, [q.id]: o.label })}>{o.label}</button>)}</div>}<input value={answers[q.id] || ""} onChange={e => setAnswers({ ...answers, [q.id]: e.target.value })}/></Field>)}{item.method === "pi/input" && <Field label={String(item.payload.title || tr("field.input"))}><input value={answers.value || ""} onChange={e => setAnswers({ ...answers, value: e.target.value })}/></Field>}{error && <div role="alert" className="form-error">{trError(error)}</div>}<div className="approval-actions"><Button onClick={() => void answer(false)} busy={busy}>{tr("common.reject")}</Button><Button className="primary" onClick={() => void answer(true)} busy={busy}>{item.kind === "input" ? tr("common.submit") : tr("approval.action.once")}</Button></div></Panel>;
}
