import { formatTime } from "./i18n";
import { tr, trError } from "./i18n";
import { useEffect, useState } from "react";
import { ArrowClockwiseIcon, ArrowLeftIcon, ArrowRightIcon, BookOpenIcon, CaretRightIcon, ChatCircleTextIcon, CheckIcon, ClockIcon, DownloadSimpleIcon, FolderIcon, FunnelIcon, GitBranchIcon, MagnifyingGlassIcon, PlusIcon, SlidersHorizontalIcon, StarIcon, TrashIcon, ArchiveIcon, XIcon, ShieldCheckIcon } from "@phosphor-icons/react";
import { useI18n } from "./i18n";
import { api, useResource, errorKey, errorText, relative, number } from "./api";
import { Badge, Button, Confirm, Dropdown, Empty, Field, Header, IconButton, Modal, Panel, Toggle } from "./components";
import type { CollectionSource, Session, SessionEvent, SessionList, SessionTimeline } from "../shared/types";

const coverage: Record<string, string> = { get indexed() { return tr("session.coverage.indexed"); }, get partial() { return tr("session.coverage.partial"); }, get error() { return tr("session.coverage.error"); }, get missing() { return tr("session.coverage.missing"); }, get restricted() { return tr("state.unauthorized"); } };
const roles: Record<string, string> = { user: "YOU", assistant: "AGENT", system: "SYSTEM", tool: "TOOL", unknown: "UNKNOWN" };
const kinds: Record<string, string> = { get message() { return tr("session.event.message"); }, get tool_call() { return tr("session.event.toolCall"); }, get tool_result() { return tr("session.event.toolResult"); }, get compaction() { return tr("session.event.compaction"); }, get branch() { return tr("session.event.branch"); }, get metadata() { return tr("session.event.metadata"); }, get unknown() { return tr("session.event.unknown"); }, get parse_error() { return tr("session.event.parseError"); } };
export function SessionsPage() {
  const { t } = useI18n();
  const [query, setQuery] = useState(""), [debounced, setDebounced] = useState(""), [agent, setAgent] = useState("all"), [filter, setFilter] = useState("active"), [offset, setOffset] = useState(0);
  const [sourceOpen, setSourceOpen] = useState(false), [selected, setSelected] = useState<string>(), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { const timeout = setTimeout(() => { setDebounced(query); setOffset(0); }, 250); return () => clearTimeout(timeout); }, [query]);
  const params = new URLSearchParams({ paged: "1", query: debounced, offset: String(offset), limit: "40", ...(agent === "all" ? {} : { agent }), ...(filter === "starred" ? { starred: "true" } : { archived: String(filter === "archived") }) });
  const sessions = useResource<SessionList>(`/sessions?${params}`, 10000);
  const sources = useResource<CollectionSource[]>("/sources", 10000);
  const enabled = sources.data?.filter(s => s.enabled).length || 0;
  const refresh = () => { sessions.refresh(); sources.refresh(); };
  return <><div className="page-heading"><div><div className="eyebrow">{t("page.sessions.eyebrow")}</div><h1>{t("page.sessions.title")}</h1></div><div className="heading-actions"><Button icon={<SlidersHorizontalIcon size={16}/>} onClick={() => setSourceOpen(true)}>{tr("source.title")}<Badge>{enabled}</Badge></Button><IconButton label={tr("session.action.refresh")} disabled={busy} onClick={async () => { setBusy(true); setError(""); try { for (const source of sources.data?.filter(s => s.enabled) || []) await api(`/sources/${source.id}/scan`, { method: "POST" }); refresh(); } catch (e) { setError(errorKey(e)); } finally { setBusy(false); } }}><ArrowClockwiseIcon className={busy ? "spin" : ""} size={18}/></IconButton></div></div>
    {(error || sessions.error) && <div role="alert" className="error-banner"><span>{error || errorText(new Error(sessions.error))}</span><Button onClick={() => { setError(""); refresh(); }}>{tr("common.retry")}</Button></div>}
    <div className="session-filters"><div className="session-search"><MagnifyingGlassIcon size={18}/><input aria-label={tr("session.search.label")} placeholder={tr("session.search.placeholder")} value={query} onChange={e => setQuery(e.target.value)}/>{query && <IconButton label={tr("common.clearSearch")} onClick={() => setQuery("")}><XIcon size={14}/></IconButton>}</div><Dropdown label={tr("session.filter.agent")} value={agent} onChange={v => { setAgent(v); setOffset(0); }} items={[{ value: "all", label: tr("session.filter.allAgents") }, { value: "claude", label: "Claude Code" }, { value: "codex", label: "Codex" }, { value: "pi", label: "Pi" }]}/><Dropdown label={tr("session.filter.state")} value={filter} onChange={v => { setFilter(v); setOffset(0); }} items={[{ value: "active", label: tr("nav.sessions") }, { value: "starred", label: tr("session.star") }, { value: "archived", label: tr("session.archive") }]}/></div>
    <Panel><Header title={tr("nav.sessions")} count={sessions.data?.total}><span className="mono muted">{enabled} SOURCES</span></Header>{sessions.data?.items.length ? <div className="sessions-list">{sessions.data.items.map(s => <button className="session-row" key={s.id} onClick={() => setSelected(s.id)}><span className="session-icon">{s.starred ? <StarIcon size={20} weight="fill"/> : <ChatCircleTextIcon size={21} weight="light"/>}</span><div className="session-content"><strong>{s.title}</strong><div><Badge>{s.agent}</Badge>{s.project && <span className="mono"><FolderIcon size={12}/>{s.project.split("/").slice(-2).join("/")}</span>}{s.status !== "indexed" && <Badge>{coverage[s.status]}</Badge>}{!s.captured && <Badge>{tr("session.event.metadata")}</Badge>}</div></div><span className="session-model mono">{number(s.eventCount)} EVENTS</span><span className="mono muted">{relative(s.lastActiveAt)}</span><CaretRightIcon size={14}/></button>)}</div> : <Empty icon={<ChatCircleTextIcon size={28} weight="light"/>} title={query ? tr("search.empty") : tr("session.empty")} action={!enabled && <Button icon={<PlusIcon size={14}/>} onClick={() => setSourceOpen(true)}>{tr("source.action.add")}</Button>}/>}
    {(offset > 0 || sessions.data?.next !== null && sessions.data?.next !== undefined) && <div className="pagination"><Button disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 40))}><ArrowLeftIcon size={14}/></Button><span className="mono">{offset + 1}–{offset + (sessions.data?.items.length || 0)}</span><Button disabled={sessions.data?.next == null} onClick={() => setOffset(sessions.data!.next!)}><ArrowRightIcon size={14}/></Button></div>}</Panel>
    {sourceOpen && <Sources open close={() => setSourceOpen(false)} changed={refresh}/>} {selected && <SessionDetail id={selected} close={() => setSelected(undefined)} changed={refresh}/>}
  </>;
}
function Sources({ open, close, changed }: { open: boolean; close: () => void; changed: () => void }) {
  const sources = useResource<CollectionSource[]>("/sources", 5000);
  const [editing, setEditing] = useState<CollectionSource | "new">();
  return <><Modal title={tr("source.title")} open={open} onOpenChange={close}><div className="source-list">{sources.data?.map(source => <button className="source-row" key={source.id} onClick={() => setEditing(source)}><span className={`source-light ${source.enabled ? "enabled" : ""}`}/><div><strong>{source.name}</strong><span className="mono">{source.path}</span><div className="source-capabilities">{source.enabled && <Badge tone="green">{source.captureBodies ? tr("source.content") : tr("session.event.metadata")}</Badge>}{source.learn && <Badge>{tr("source.candidates")}</Badge>}{source.lastError && <Badge>{source.lastError === "source_unavailable" ? tr("source.unavailable") : source.lastError}</Badge>}</div></div><CaretRightIcon size={14}/></button>)}</div><div className="form-actions"><Button icon={<PlusIcon size={15}/>} onClick={() => setEditing("new")}>{tr("source.action.addDirectory")}</Button></div></Modal>{editing && <SourceForm source={editing === "new" ? undefined : editing} close={() => setEditing(undefined)} saved={() => { setEditing(undefined); sources.refresh(); changed(); }}/>}</>;
}
function SourceForm({ source, close, saved }: { source?: CollectionSource; close: () => void; saved: () => void }) {
  const [name, setName] = useState(source?.name || ""), [path, setPath] = useState(source?.path || ""), [agent, setAgent] = useState(source?.agent || "auto");
  const [enabled, setEnabled] = useState(source?.enabled ?? true), [capture, setCapture] = useState(source?.captureBodies ?? false), [learn, setLearn] = useState(source?.learn ?? false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  return <Modal title={source ? source.name : tr("source.action.add")} open onOpenChange={close}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); try { const next = await api<CollectionSource>(source ? `/sources/${source.id}` : "/sources", { method: source ? "PATCH" : "POST", body: JSON.stringify({ name, path, agent, enabled, captureBodies: capture, learn, revision: source?.revision }) }); if (next.enabled) await api(`/sources/${next.id}/scan`, { method: "POST" }); saved(); } catch (error) { setError(errorKey(error)); } finally { setBusy(false); } }}><div className="form-grid"><Field label={tr("field.name")}><input required value={name} onChange={e => setName(e.target.value)}/></Field><Field label={tr("source.field.format")}><Dropdown value={agent} onChange={v => setAgent(v as CollectionSource["agent"])} items={[{ value: "auto", label: tr("source.format.auto") }, { value: "claude", label: "Claude Code" }, { value: "codex", label: "Codex" }, { value: "pi", label: "Pi" }]}/></Field></div><Field label={tr("source.field.directory")}><input required className="mono" value={path} onChange={e => setPath(e.target.value)} disabled={source?.enabled}/></Field><div className="permission-options"><div><div><strong>{tr("source.collect")}</strong></div><Toggle checked={enabled} onChange={setEnabled} label={tr("source.collect")}/></div><div><div><strong>{tr("source.capture")}</strong><span>{tr("source.capturePurpose")}</span></div><Toggle checked={capture} onChange={v => { setCapture(v); if (!v) setLearn(false); }} label={tr("source.capture")}/></div><div><div><strong>{tr("source.learn")}</strong><span>{tr("source.confirmationRequired")}</span></div><Toggle checked={learn} disabled={!capture} onChange={setLearn} label={tr("source.learn")}/></div></div>{source?.captureBodies && !capture && <div className="form-warning">{tr("source.warning.revoke")}</div>}{error && <div role="alert" className="form-error">{trError(error)}</div>}<div className="form-actions">{source && <Confirm title={tr("source.confirm.delete")} onConfirm={async () => { await api(`/sources/${source.id}`, { method: "DELETE" }); saved(); }}><button className="icon-button danger-icon" type="button" aria-label={tr("source.action.delete")}><TrashIcon size={17}/></button></Confirm>}{source && <Confirm title={tr("source.confirm.reset")} onConfirm={async () => { await api(`/sources/${source.id}/restore-deleted`, { method: "POST" }); }}><button className="text-button" type="button">{tr("source.action.reset")}</button></Confirm>}<Button type="button" onClick={close}>{tr("common.cancel")}</Button><Button type="submit" className="primary" busy={busy}>{tr("common.save")}</Button></div></form></Modal>;
}
function SessionDetail({ id, close, changed }: { id: string; close: () => void; changed: () => void }) {
  const [leaf, setLeaf] = useState("all"), [after, setAfter] = useState<number>(), [events, setEvents] = useState<SessionEvent[]>([]), [error, setError] = useState("");
  const params = new URLSearchParams({ limit: "100", ...(after !== undefined ? { after: String(after) } : {}), ...(leaf !== "all" ? { leaf } : {}) });
  const detail = useResource<SessionTimeline>(`/sessions/${id}/timeline?${params}`);
  useEffect(() => { if (detail.data) setEvents(previous => after === undefined ? detail.data!.events : [...previous.filter(e => !detail.data!.events.some(n => n.id === e.id)), ...detail.data!.events]); }, [detail.data]);
  const session = detail.data?.session;
  const edit = async (patch: object) => { try { await api(`/sessions/${id}`, { method: "PATCH", body: JSON.stringify(patch) }); detail.refresh(); changed(); } catch (error) { setError(errorKey(error)); } };
  const exportSession = () => {
    const link = document.createElement("a");
    link.href = `/api/sessions/${id}/export?limit=200`;
    link.download = `session-${id}.jsonl`;
    link.click();
  };
  return <Modal title={session?.title || tr("nav.sessions")} wide open onOpenChange={close}>{session && <><div className="session-detail-tools"><Badge>{session.agent}</Badge><Badge>{coverage[session.status]}</Badge><span className="mono muted">{session.eventCount} EVENTS</span><div><IconButton label={session.starred ? tr("session.unstar") : tr("session.star")} onClick={() => void edit({ starred: !session.starred })}><StarIcon size={17} weight={session.starred ? "fill" : "regular"}/></IconButton><IconButton label={session.archived ? tr("session.unarchive") : tr("session.archive")} onClick={() => void edit({ archived: !session.archived })}><ArchiveIcon size={17}/></IconButton><IconButton label={tr("session.export")} onClick={() => void exportSession()}><DownloadSimpleIcon size={17}/></IconButton><Confirm title={tr("session.confirm.forget")} onConfirm={async () => { await api(`/sessions/${id}`, { method: "DELETE" }); changed(); close(); }}><button className="icon-button danger-icon" aria-label={tr("session.forget")}><TrashIcon size={17}/></button></Confirm></div></div><div className="session-detail-meta"><span className="mono">{session.project || "—"}</span><span className="mono">{session.model || "—"}</span></div>{(detail.data?.branches.length || 0) > 1 && <div className="branch-picker"><GitBranchIcon size={16}/><Dropdown value={leaf} onChange={value => { setLeaf(value); setAfter(undefined); setEvents([]); }} items={[{ value: "all", label: tr("session.branches.all") }, ...detail.data!.branches.map(b => ({ value: b.id, label: b.id.slice(0, 32) }))]}/></div>}{!session.captured && <div className="metadata-mode"><ShieldCheckIcon size={16}/>{tr("session.metadataOnly")}</div>}{error && <div role="alert" className="form-error">{trError(error)}</div>}<div className="session-timeline">{events.map(event => <EventView key={event.id} event={event}/>)}</div>{detail.data?.next !== null && detail.data?.next !== undefined && <div className="form-actions"><Button onClick={() => setAfter(detail.data!.next!)}>{tr("common.more")}<ArrowRightIcon size={14}/></Button></div>}{!events.length && <Empty icon={<ChatCircleTextIcon size={24}/>} title={tr("session.events.empty")}/>}</>}</Modal>;
}
function EventView({ event }: { event: SessionEvent }) {
  const [saved, setSaved] = useState(false), [error, setError] = useState("");
  if (event.kind === "message") return <div className={`timeline-message role-${event.role}`}><div className="timeline-event-heading"><span className="mono">{roles[event.role]}</span>{event.origin !== event.role && <Badge>{tr("session.origin.unknown")}</Badge>}{event.origin === "user" && event.text && <Confirm title={tr("session.confirm.remember")} onConfirm={async () => { await api("/preferences/from-event", { method: "POST", body: JSON.stringify({ eventId: event.id, scope: "global" }) }); setSaved(true); }}><button className="icon-button" aria-label={saved ? tr("session.remembered") : tr("session.remember")} disabled={saved}>{saved ? <CheckIcon size={14}/> : <BookOpenIcon size={14}/>}</button></Confirm>}<time className="mono">{event.timestamp ? formatTime(event.timestamp) : ""}</time></div>{event.text ? <pre>{event.text}</pre> : <span className="muted">{tr("session.content.absent")}</span>}{event.metadata.truncated === true && <Badge>{tr("session.content.truncated")}</Badge>}</div>;
  return <details className={`timeline-event kind-${event.kind}`}><summary><span className="timeline-kind-dot"/><span>{kinds[event.kind]}</span><span className="mono">{String(event.metadata.name || event.metadata.toolName || event.metadata.nativeType || "")}</span><span className="mono event-offset">{event.offset}</span></summary><pre>{event.text || JSON.stringify(event.metadata, null, 2)}</pre></details>;
}
