import { useEffect,useState } from "react";
import { ArchiveIcon,ArrowClockwiseIcon,ArrowLeftIcon,ArrowRightIcon,BookOpenIcon,CheckIcon,CopyIcon,DownloadSimpleIcon,FolderIcon,GitDiffIcon,PlusIcon,SlidersHorizontalIcon } from "@phosphor-icons/react";
import { api,useResource,errorKey,relative } from "./api";
import { tr,trError } from "./i18n";
import { Badge,Button,Confirm,Dropdown,Empty,Field,Header,IconButton,Modal,Panel,Toggle } from "./components";
import type { Asset,AssetRoot,AssetDeployment,AssetSnapshot } from "../shared/types";

type Skill=Asset&{duplicateCount:number};
type Snapshot=Omit<AssetSnapshot,"contentCipher">;
interface SkillDetails {asset:Asset;content:string;metadata:{warnings:string[];tools:string[]};snapshots:Snapshot[];duplicates:Asset[];conflicts:Asset[]}
export function SkillsPanel(){
  const [query,setQuery]=useState(""),[search,setSearch]=useState(""),[offset,setOffset]=useState(0),[filter,setFilter]=useState("all"),[selected,setSelected]=useState<string>(),[roots,setRoots]=useState(false),[deployments,setDeployments]=useState(false);
  useEffect(()=>{const timer=setTimeout(()=>{setSearch(query);setOffset(0);},250);return()=>clearTimeout(timer);},[query]);
  const page=useResource<{items:Skill[];total:number;next:number|null}>(`/skills?${new URLSearchParams({query:search,offset:String(offset),limit:"40",duplicates:String(filter==="duplicates")})}`);
  return <><Header title="Skills" count={page.data?.total}><Button icon={<SlidersHorizontalIcon size={15}/>} onClick={()=>setRoots(true)}>{tr("source.title")}</Button><Button icon={<ArchiveIcon size={15}/>} onClick={()=>setDeployments(true)}>{tr("assets.installs.title")}</Button></Header><div className="session-filters"><div className="session-search"><BookOpenIcon size={17}/><input aria-label={tr("assets.search")} placeholder={tr("assets.search")} value={query} onChange={e=>setQuery(e.target.value)}/></div><Dropdown value={filter} onChange={value=>{setFilter(value);setOffset(0);}} items={[{value:"all",label:tr("common.all")},{value:"duplicates",label:tr("assets.duplicates.filter")}]}/></div><div className="asset-grid">{page.data?.items.map(skill=><Panel key={skill.id} className="skill-card"><button className="skill-card-open" onClick={()=>setSelected(skill.id)}><div className="asset-card-icon"><BookOpenIcon size={24} weight="light"/></div><h3>{skill.name}</h3><p>{skill.description}</p><div className="asset-card-meta"><Badge>{skill.source}</Badge><span className="mono">{skill.version||skill.hash?.slice(0,10)||"—"}</span></div>{skill.duplicateCount>1&&<Badge>{tr("assets.duplicates.count",{count:skill.duplicateCount})}</Badge>}</button></Panel>)}</div>{!page.data?.items.length&&<Panel><Empty icon={<BookOpenIcon size={26} weight="light"/>} title={page.error?tr("error.operation"):tr("registry.empty")} action={<Button onClick={()=>setRoots(true)}>{tr("source.title")}</Button>}/></Panel>}{(offset>0||page.data?.next!=null)&&<div className="pagination"><Button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-40))}><ArrowLeftIcon size={14}/></Button><span className="mono">{offset+1}–{offset+(page.data?.items.length||0)}</span><Button disabled={page.data?.next==null} onClick={()=>setOffset(page.data!.next!)}><ArrowRightIcon size={14}/></Button></div>}{selected&&<SkillDetail id={selected} close={()=>setSelected(undefined)} changed={page.refresh}/>} {roots&&<AssetSources close={()=>setRoots(false)} changed={page.refresh}/>} {deployments&&<Deployments close={()=>setDeployments(false)}/>}</>;
}
function AssetSources({close,changed}:{close:()=>void;changed:()=>void}){
  const sources=useResource<AssetRoot[]>("/asset-roots",5000);
  const [editing,setEditing]=useState<AssetRoot|"new">(),[busy,setBusy]=useState<string>(),[error,setError]=useState("");
  return <><Modal title={tr("assets.sources.title")} open onOpenChange={close}><div className="source-list">{sources.data?.map(source=><div className="asset-source-row" key={source.id}><button className="source-row" onClick={()=>setEditing(source)}><span className={`source-light ${source.enabled?"enabled":""}`}/><div><strong>{source.name}</strong><span className="mono">{source.path}</span><div className="source-capabilities"><Badge>{source.agent}</Badge>{source.capture&&<Badge>{tr("assets.snapshot.auto")}</Badge>}{source.lastError&&<Badge>{source.lastError}</Badge>}</div></div></button><IconButton label={tr("common.scan")} disabled={busy===source.id||!source.enabled} onClick={async()=>{setBusy(source.id);setError("");try{await api(`/asset-roots/${source.id}/scan`,{method:"POST"});sources.refresh();changed();}catch(e){setError(errorKey(e));}finally{setBusy(undefined);}}}><ArrowClockwiseIcon size={16} className={busy===source.id?"spin":""}/></IconButton></div>)}</div>{error&&<div className="form-error">{trError(error)}</div>}<div className="form-actions"><Button icon={<PlusIcon size={14}/>} onClick={()=>setEditing("new")}>{tr("source.action.addDirectory")}</Button></div></Modal>{editing&&<AssetSourceForm source={editing==="new"?undefined:editing} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);sources.refresh();changed();}}/>}</>;
}
function AssetSourceForm({source,close,saved}:{source?:AssetRoot;close:()=>void;saved:()=>void}){
  const [name,setName]=useState(source?.name||""),[path,setPath]=useState(source?.path||""),[agent,setAgent]=useState(source?.agent||"shared"),[project,setProject]=useState(source?.project||"");
  const [enabled,setEnabled]=useState(source?.enabled??true),[follow,setFollow]=useState(source?.followSymlinks||false),[capture,setCapture]=useState(source?.capture||false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  return <Modal title={source?.name||tr("source.action.addDirectory")} open onOpenChange={close}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api(source?`/asset-roots/${source.id}`:"/asset-roots",{method:source?"PATCH":"POST",body:JSON.stringify({name,path,agent,project:project||null,enabled,followSymlinks:follow,capture,revision:source?.revision})});saved();}catch(e){setError(errorKey(e));}finally{setBusy(false);}}}><div className="form-grid"><Field label={tr("field.name")}><input required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Agent"><Dropdown value={agent} onChange={value=>setAgent(value as AssetRoot["agent"])} items={[{value:"shared",label:tr("assets.shared")},{value:"claude",label:"Claude Code"},{value:"codex",label:"Codex"},{value:"pi",label:"Pi"}]}/></Field></div><Field label={tr("field.path")}><input required className="mono" value={path} onChange={e=>setPath(e.target.value)}/></Field><Field label={tr("field.projectPath")}><input className="mono" value={project} onChange={e=>setProject(e.target.value)}/></Field><div className="permission-options"><div><strong>{tr("common.enable")}</strong><Toggle checked={enabled} onChange={setEnabled} label={tr("common.enable")}/></div><div><strong>{tr("assets.links.follow")}</strong><Toggle checked={follow} onChange={setFollow} label={tr("assets.links.follow")}/></div><div><strong>{tr("assets.snapshot.auto")}</strong><Toggle checked={capture} onChange={setCapture} label={tr("assets.snapshot.auto")}/></div></div>{capture&&<div className="form-warning">{tr("assets.snapshot.notice")}</div>}{error&&<div className="form-error">{trError(error)}</div>}<div className="form-actions"><Button type="button" onClick={close}>{tr("common.cancel")}</Button><Button className="primary" type="submit" busy={busy}>{tr("common.save")}</Button></div></form></Modal>;
}
function SkillDetail({id,close,changed}:{id:string;close:()=>void;changed:()=>void}){
  const details=useResource<SkillDetails>(`/assets/${id}`);
  const [tab,setTab]=useState("content"),[install,setInstall]=useState<Snapshot>(),[snapshot,setSnapshot]=useState<string>();
  const value=details.data;
  return <><Modal title={value?.asset.name||"Skill"} wide open onOpenChange={close}>{value&&<><div className="session-detail-tools"><Badge>{value.asset.source}</Badge><span className="mono muted">{value.asset.version||value.asset.hash?.slice(0,12)}</span><span className="skill-detail-actions"><Confirm title={tr("assets.snapshot.confirm")} onConfirm={async()=>{await api(`/assets/${id}/snapshot`,{method:"POST",body:JSON.stringify({confirmed:true})});details.refresh();changed();}}><button className="button"><ArchiveIcon size={14}/>{tr("assets.snapshot.create")}</button></Confirm></span></div><div className="mono skill-path">{value.asset.path}</div><div className="debug-tabs"><button className={tab==="content"?"active":""} onClick={()=>setTab("content")}>{tr("field.content")}</button><button className={tab==="versions"?"active":""} onClick={()=>setTab("versions")}>{tr("assets.snapshot.history")} <span className="mono">{value.snapshots.length}</span></button><button className={tab==="related"?"active":""} onClick={()=>setTab("related")}>{tr("assets.related")} <span className="mono">{value.duplicates.length+value.conflicts.length}</span></button></div>{tab==="content"?<><div className="skill-tools">{value.metadata.tools.map(tool=><Badge key={tool}>{tool}</Badge>)}</div><pre className="skill-content">{value.content}</pre></>:tab==="versions"?<div>{value.snapshots.map(s=><div key={s.id} className="skill-snapshot-row"><button onClick={()=>setSnapshot(s.id)}><strong className="mono">{s.hash.slice(0,12)}</strong><span>{s.version||"—"} · {s.files.length} {tr("assets.files")}</span></button><span className="mono muted">{relative(s.createdAt)}</span><Button onClick={()=>setInstall(s)}>{tr("assets.install")}</Button></div>)}{!value.snapshots.length&&<Empty icon={<ArchiveIcon size={24}/>} title={tr("assets.snapshot.empty")}/>}</div>:<div>{[...value.duplicates.map(asset=>({asset,same:true})),...value.conflicts.map(asset=>({asset,same:false}))].map(({asset,same})=><div className="skill-related-row" key={asset.id}><Badge tone={same?"green":"muted"}>{tr(same?"assets.duplicates.label":"assets.conflict.label")}</Badge><div><strong>{asset.name}</strong><span className="mono">{asset.path}</span></div></div>)}</div>}</>}{details.error&&<div role="alert" className="form-error">{trError(errorKey(new Error(details.error)))}</div>}</Modal>{install&&value&&<InstallForm asset={value.asset} snapshot={install} close={()=>setInstall(undefined)}/>} {snapshot&&<SnapshotDetail id={snapshot} close={()=>setSnapshot(undefined)}/>}</>;
}
function SnapshotDetail({id,close}:{id:string;close:()=>void}){
  const detail=useResource<Snapshot&{content:string}>(`/asset-snapshots/${id}`);
  return <Modal title={tr("assets.snapshot.title")} wide open onOpenChange={close}><div className="snapshot-files">{detail.data?.files.map(file=><div key={file.path}><span className="mono">{file.path}</span><span className="mono muted">{file.size} B</span></div>)}</div><pre className="skill-content">{detail.data?.content||"…"}</pre></Modal>;
}
function InstallForm({asset,snapshot,close}:{asset:Asset;snapshot:Snapshot;close:()=>void}){
  const [root,setRoot]=useState(""),[name,setName]=useState(asset.path.split("/").at(-2)||asset.name),[agent,setAgent]=useState("codex"),[plan,setPlan]=useState<AssetDeployment>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
  return <Modal title={tr("assets.install.title")} open onOpenChange={close}>{!plan?<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{setPlan(await api(`/assets/${asset.id}/deploy`,{method:"POST",body:JSON.stringify({snapshotId:snapshot.id,targetRoot:root,name,agent})}));}catch(e){setError(errorKey(e));}finally{setBusy(false);}}}><Field label="Agent"><Dropdown value={agent} onChange={setAgent} items={[{value:"codex",label:"Codex"},{value:"claude",label:"Claude Code"},{value:"pi",label:"Pi"},{value:"shared",label:tr("assets.shared")}]}/></Field><Field label={tr("assets.target.root")}><input required className="mono" placeholder="/path/to/skills" value={root} onChange={e=>setRoot(e.target.value)}/></Field><Field label={tr("assets.target.name")}><input required value={name} onChange={e=>setName(e.target.value)}/></Field>{error&&<div className="form-error">{trError(error)}</div>}<div className="form-actions"><Button type="button" onClick={close}>{tr("common.cancel")}</Button><Button className="primary" type="submit" busy={busy}>{tr("assets.preview")}</Button></div></form>:<><div className="mono skill-path">{plan.target}</div><div className="snapshot-files">{plan.diff.map(diff=><div key={diff.path} className={`file-change ${diff.action}`}><span>{diff.action==="add"?"+":diff.action==="remove"?"−":"~"}</span><span className="mono">{diff.path}</span></div>)}</div>{plan.status==="applied"?<div className="install-done"><CheckIcon size={20}/>{tr("assets.installed")}</div>:<div className="form-actions"><Button onClick={()=>setPlan(undefined)}>{tr("common.edit")}</Button><Confirm title={tr("assets.install.confirm")} onConfirm={async()=>{setPlan(await api(`/asset-deployments/${plan.id}/apply`,{method:"POST",body:JSON.stringify({confirmed:true})}));}}><button className="button primary"><DownloadSimpleIcon size={15}/>{tr("assets.install")}</button></Confirm></div>}</>}</Modal>;
}
function Deployments({close}:{close:()=>void}){
  const entries=useResource<AssetDeployment[]>("/asset-deployments",3000);
  const states:Record<string,import("./i18n").I18nKey>={prepared:"assets.prepared",applying:"state.executing",applied:"assets.installed",restoring:"state.executing",restored:"assets.restored",failed:"state.failed",uncertain:"state.uncertain"};
  return <Modal title={tr("assets.installs.title")} wide open onOpenChange={close}>{entries.data?.map(entry=><div className="deployment-row" key={entry.id}><div><strong>{entry.target.split("/").at(-1)}</strong><span className="mono">{entry.target}</span>{entry.error&&<span className="form-warning">{entry.error}</span>}</div><Badge tone={entry.status==="applied"||entry.status==="restored"?"green":"muted"}>{states[entry.status]?tr(states[entry.status]):entry.status}</Badge>{entry.status==="applied"&&<Confirm title={tr("assets.restore.confirm")} onConfirm={async()=>{await api(`/asset-deployments/${entry.id}/restore`,{method:"POST",body:JSON.stringify({confirmed:true})});entries.refresh();}}><button className="button"><ArrowClockwiseIcon size={14}/>{tr("common.restore")}</button></Confirm>}</div>)}{!entries.data?.length&&<Empty icon={<ArchiveIcon size={27}/>} title={tr("assets.installs.empty")}/>}</Modal>;
}
