import { GitBranchIcon, ArrowRightIcon, ArrowClockwiseIcon, TrashIcon } from "@phosphor-icons/react";
import { useState } from "react";
import { tr, formatTime } from "./i18n";
import { api, useResource, money, number } from "./api";
import { Modal, Badge, Confirm, Header, Empty, Copy } from "./components";
import type { Traffic } from "../shared/types";
const actionKeys={select:"routing.action.select",skip:"routing.action.skip",fallback:"routing.action.fallback",convert:"routing.action.convert",personalization:"routing.action.personalize"} as const;
export function TrafficDetail({id,close}:{id:string;close:()=>void}){
  const trace=useResource<{request:Traffic;attempts:Traffic[]}>(`/traffic/${id}`,1500);
  const item=trace.data?.request;
  return <Modal title={item?.model||tr("traffic.request.title")} wide open onOpenChange={close}>{item&&<><div className="session-detail-tools"><Badge>{item.protocol}</Badge><span className="mono muted">{item.requestGroupId||item.id}</span><Copy value={item.requestGroupId||item.id} label={tr("traffic.field.requestId")}/></div><div className="run-meters"><div><span>{tr("field.cost")}</span><strong className="mono">{item.costMicros===null?"—":money(item.costMicros)}</strong></div><div><span>{tr("traffic.field.inputTokens")}</span><strong className="mono">{item.inputTokens===null?"—":number(item.inputTokens)}</strong></div><div><span>{tr("traffic.field.outputTokens")}</span><strong className="mono">{item.outputTokens===null?"—":number(item.outputTokens)}</strong></div></div><dl className="detail-list"><div><dt>{tr("traffic.field.firstByte")}</dt><dd className="mono">{item.firstByteMs===null?"—":`${item.firstByteMs}ms`}</dd></div><div><dt>{tr("field.client")}</dt><dd>{item.clientName}</dd></div><div><dt>{tr("provider.title")}</dt><dd>{item.providerName}</dd></div><div><dt>{tr("routing.field.affinity")}</dt><dd className="mono">{item.affinityId||"—"}</dd></div><div><dt>{tr("routing.field.response")}</dt><dd className="mono">{item.responseId||"—"}</dd></div><div><dt>{tr("route.cache.read")}</dt><dd className="mono">{number(item.cacheReadTokens)}</dd></div><div><dt>{tr("route.cache.write")}</dt><dd className="mono">{number(item.cacheWriteTokens)}</dd></div><div><dt>{tr("route.cache.longWrite")}</dt><dd className="mono">{number(item.cacheWriteLongTokens)}</dd></div>{item.error&&<div><dt>{tr("field.error")}</dt><dd>{item.error}</dd></div>}</dl><Header title={tr("traffic.attempts.title")} count={trace.data?.attempts.length}/><div className="routing-attempts">{trace.data?.attempts.map((attempt,index)=><div key={attempt.id} className="routing-attempt"><div><span className="mono">{String(index+1).padStart(2,"0")}</span><strong>{attempt.providerName}</strong><Badge tone={attempt.status==="completed"?"green":"muted"}>{tr(attempt.status==="completed"?"common.done":attempt.status==="running"?"state.running":attempt.status==="cancelled"?"state.cancelled":"state.failed")}</Badge><time className="mono">{formatTime(attempt.createdAt)}</time></div>{attempt.decisions.map((decision,i)=><div className="routing-decision" key={i}><GitBranchIcon size={13}/><span>{decision.action in actionKeys?tr(actionKeys[decision.action as keyof typeof actionKeys]):decision.action}</span><code>{decision.reason}</code></div>)}</div>)}</div><details className="run-events"><summary>{tr("routing.field.priceSnapshot")}</summary><pre className="run-output">{JSON.stringify(item.pricing,null,2)}</pre></details></>}</Modal>;
}
export function RoutingHealth({close}:{close:()=>void}){
  const sessions=useResource<{id:string;routeId:string;model:string|null;active:number;uncertain:number;updatedAt:number}[]>("/routing/sessions",2000);
  const circuits=useResource<{id:string;providerName:string;model:string;failures:number;openUntil:number;lastError:string|null}[]>("/routing/circuits",2000);
  const [tab,setTab]=useState("circuits");
  return <Modal title={tr("routing.title")} wide open onOpenChange={close}><div className="debug-tabs"><button className={tab==="circuits"?"active":""} onClick={()=>setTab("circuits")}>{tr("routing.circuits")}</button><button className={tab==="sessions"?"active":""} onClick={()=>setTab("sessions")}>{tr("routing.sessions")}</button></div>{tab==="circuits"?<div>{circuits.data?.map(c=><div className="routing-health-row" key={c.id}><div><strong>{c.providerName}</strong><span className="mono">{c.model}</span></div><Badge tone={c.openUntil>Date.now()?"muted":"green"}>{c.openUntil>Date.now()?tr("routing.cooldown"):tr("state.online")}</Badge><span className="mono muted">{c.failures}</span><Confirm title={tr("routing.confirm.reset")} onConfirm={async()=>{await api(`/routing/circuits/${c.id}/reset`,{method:"POST"});circuits.refresh();}}><button className="icon-button" aria-label={tr("routing.reset")}><ArrowClockwiseIcon size={16}/></button></Confirm></div>)}</div>:<div>{sessions.data?.map(s=><div className="routing-health-row" key={s.id}><div><strong>{s.model||"—"}</strong><span className="mono">{s.id}</span></div><Badge tone={s.uncertain?"muted":"green"}>{s.uncertain?tr("state.uncertain"):s.active?tr("state.running"):tr("routing.pinned")}</Badge><Confirm title={tr("routing.confirm.closeSession")} onConfirm={async()=>{await api(`/routing/sessions/${s.id}`,{method:"DELETE"});sessions.refresh();}}><button className="icon-button danger-icon" aria-label={tr("routing.closeSession")} disabled={!!s.active}><TrashIcon size={16}/></button></Confirm></div>)}</div>}</Modal>;
}
